# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 188)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 491, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chord_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chord_label.sizePolicy().hasHeightForWidth())
        self.chord_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(72)
        self.chord_label.setFont(font)
        self.chord_label.setAlignment(QtCore.Qt.AlignCenter)
        self.chord_label.setObjectName("chord_label")
        self.verticalLayout_4.addWidget(self.chord_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beat_string = QtWidgets.QLabel(self.widget)
        self.beat_string.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.beat_string.sizePolicy().hasHeightForWidth())
        self.beat_string.setSizePolicy(sizePolicy)
        self.beat_string.setAlignment(QtCore.Qt.AlignCenter)
        self.beat_string.setObjectName("beat_string")
        self.horizontalLayout.addWidget(self.beat_string)
        self.beats_per_change = QtWidgets.QSpinBox(self.widget)
        self.beats_per_change.setMinimum(1)
        self.beats_per_change.setMaximum(6)
        self.beats_per_change.setProperty("value", 4)
        self.beats_per_change.setObjectName("beats_per_change")
        self.horizontalLayout.addWidget(self.beats_per_change)
        self.tempo_bpm = QtWidgets.QSpinBox(self.widget)
        self.tempo_bpm.setMinimum(40)
        self.tempo_bpm.setMaximum(208)
        self.tempo_bpm.setSingleStep(4)
        self.tempo_bpm.setProperty("value", 60)
        self.tempo_bpm.setObjectName("tempo_bpm")
        self.horizontalLayout.addWidget(self.tempo_bpm)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chord_label.setText(_translate("MainWindow", "TextLabel"))
        self.beat_string.setText(_translate("MainWindow", "TextLabel"))
        self.beats_per_change.setSuffix(_translate("MainWindow", " beats per change"))
        self.tempo_bpm.setSuffix(_translate("MainWindow", " bpm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
