#! /usr//bin/env python3
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import QObject, pyqtSignal

from main_window import Ui_MainWindow
from metronome import Metronome
from chord_picker import ChordPicker

import random
import sys

class Window(QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)

        self.chord_picker = ChordPicker()
        self.metronome = Metronome(
            bpm=self.tempo_bpm.value(),
            strong_period=self.beats_per_change.value())

        self.metronome.tick.connect(self.beat_string.setText)
        self.metronome.strong_tick.connect(self.chord_picker.update)
        self.chord_picker.new_chord.connect(self.chord_label.setText)

        self.beats_per_change.valueChanged.connect(self.metronome.set_strong_period)
        self.tempo_bpm.valueChanged.connect(self.metronome.set_tempo)

        self.metronome.start()

def main():
    app = QApplication([])
    random.seed()

    win = Window()
    win.show()

    sys.exit(app.exec())

if __name__ == "__main__":
    main()
